INSERT INTO Competes_In VALUES('Algeria', 2014, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ivory Coast', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ghana', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Nigeria', 2014, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Australia', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Iran', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Japan', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 2014, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Belgium', 2014, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Bosnia and Herzegovina', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 2014, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('France', 2014, 'FIFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 2014, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 2014, 'FIFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 2014, 'FIFA', 'Semi-finals', '1-7', 'W');
INSERT INTO Competes_In VALUES('Germany', 2014, 'FIFA', 'Final', '1-0', 'W');
INSERT INTO Competes_In VALUES('Greece', 2014, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2014, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2014, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2014, 'FIFA', 'Semi-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2014, 'FIFA', 'Play-off for third place', '0-3', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Russia', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 2014, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Costa Rica', 2014, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Costa Rica', 2014, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Honduras', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 2014, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('USA', 2014, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Argentina', 2014, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Argentina', 2014, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Argentina', 2014, 'FIFA', 'Semi-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 2014, 'FIFA', 'Final', '1-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2014, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2014, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2014, 'FIFA', 'Semi-finals', '1-7', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2014, 'FIFA', 'Play-off for third place', '0-3', 'L');
INSERT INTO Competes_In VALUES('Chile', 2014, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Colombia', 2014, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Colombia', 2014, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Ecuador', 2014, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 2014, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Algeria', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ghana', 2010, 'FIFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Ghana', 2010, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Ivory Coast', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Nigeria', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('South Africa', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Australia', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Japan', 2010, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea DPR', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2010, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Denmark', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 2010, 'FIFA', 'Round of 16', '4-1', 'L');
INSERT INTO Competes_In VALUES('France', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany', 2010, 'FIFA', 'Round of 16', '4-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 2010, 'FIFA', 'Quarter-finals', '0-4', 'W');
INSERT INTO Competes_In VALUES('Germany', 2010, 'FIFA', 'Semi-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 2010, 'FIFA', 'Match for third place', '2-3', 'W');
INSERT INTO Competes_In VALUES('Greece', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2010, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2010, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2010, 'FIFA', 'Semi-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2010, 'FIFA', 'Final', '0-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2010, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Serbia', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Slovakia', 2010, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Slovenia', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2010, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 2010, 'FIFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 2010, 'FIFA', 'Semi-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 2010, 'FIFA', 'Final', '0-1', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Honduras', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 2010, 'FIFA', 'Round of 16', '3-1', 'L');
INSERT INTO Competes_In VALUES('USA', 2010, 'FIFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('New Zealand', 2010, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 2010, 'FIFA', 'Round of 16', '3-1', 'W');
INSERT INTO Competes_In VALUES('Argentina', 2010, 'FIFA', 'Quarter-finals', '0-4', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2010, 'FIFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2010, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Chile', 2010, 'FIFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 2010, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 2010, 'FIFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 2010, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Uruguay', 2010, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 2010, 'FIFA', 'Semi-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 2010, 'FIFA', 'Match for third place', '2-3', 'L');
INSERT INTO Competes_In VALUES('Angola', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ghana', 2006, 'FIFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Ivory Coast', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Togo', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Tunisia', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Australia', 2006, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Iran', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Japan', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Saudi Arabia', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 2006, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('England', 2006, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 2006, 'FIFA', 'Round of 16', '1-3', 'W');
INSERT INTO Competes_In VALUES('France', 2006, 'FIFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('France', 2006, 'FIFA', 'Semi-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('France', 2006, 'FIFA', 'Final', '1-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 2006, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 2006, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 2006, 'FIFA', 'Semi-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 2006, 'FIFA', 'Third place', '3-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 2006, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 2006, 'FIFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 2006, 'FIFA', 'Semi-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 2006, 'FIFA', 'Final', '1-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2006, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Poland', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2006, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2006, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2006, 'FIFA', 'Semi-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2006, 'FIFA', 'Third place', '3-1', 'L');
INSERT INTO Competes_In VALUES('Serbia and Montenegro', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2006, 'FIFA', 'Round of 16', '1-3', 'L');
INSERT INTO Competes_In VALUES('Sweden', 2006, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 2006, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ukraine', 2006, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Ukraine', 2006, 'FIFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Costa Rica', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 2006, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Trinidad and Tobago', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('USA', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 2006, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Argentina', 2006, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2006, 'FIFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2006, 'FIFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Ecuador', 2006, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 2006, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Nigeria', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Senegal', 2002, 'FIFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Senegal', 2002, 'FIFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('South Africa', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Tunisia', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('China PR', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Japan', 2002, 'FIFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2002, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Korea Republic', 2002, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2002, 'FIFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 2002, 'FIFA', 'Third place', '2-3', 'L');
INSERT INTO Competes_In VALUES('Saudi Arabia', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 2002, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Denmark', 2002, 'FIFA', 'Round of 16', '0-3', 'L');
INSERT INTO Competes_In VALUES('England', 2002, 'FIFA', 'Round of 16', '0-3', 'W');
INSERT INTO Competes_In VALUES('England', 2002, 'FIFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('France', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany', 2002, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 2002, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 2002, 'FIFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 2002, 'FIFA', 'Final', '0-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 2002, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Poland', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 2002, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Russia', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Slovenia', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2002, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 2002, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 2002, 'FIFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('Turkey', 2002, 'FIFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2002, 'FIFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2002, 'FIFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 2002, 'FIFA', 'Third place', '2-3', 'W');
INSERT INTO Competes_In VALUES('Costa Rica', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 2002, 'FIFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('USA', 2002, 'FIFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('USA', 2002, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 2002, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2002, 'FIFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2002, 'FIFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 2002, 'FIFA', 'Final', '0-2', 'W');
INSERT INTO Competes_In VALUES('Ecuador', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 2002, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 2002, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Morocco', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Nigeria', 1998, 'FIFA', 'Round of 16', '1-4', 'L');
INSERT INTO Competes_In VALUES('South Africa', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Tunisia', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Iran', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Japan', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Saudi Arabia', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Croatia', 1998, 'FIFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Croatia', 1998, 'FIFA', 'Quarter-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Croatia', 1998, 'FIFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Croatia', 1998, 'FIFA', 'Match for third place', '1-2', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1998, 'FIFA', 'Round of 16', '1-4', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1998, 'FIFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('England', 1998, 'FIFA', 'Round of 16', '2-2', 'L');
INSERT INTO Competes_In VALUES('France', 1998, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('France', 1998, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 1998, 'FIFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('France', 1998, 'FIFA', 'Final', '0-3', 'W');
INSERT INTO Competes_In VALUES('Germany', 1998, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 1998, 'FIFA', 'Quarter-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('Italy', 1998, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1998, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1998, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1998, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1998, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1998, 'FIFA', 'Match for third place', '1-2', 'L');
INSERT INTO Competes_In VALUES('Norway', 1998, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1998, 'FIFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1998, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Jamaica', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1998, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('USA', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1998, 'FIFA', 'Round of 16', '2-2', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1998, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1998, 'FIFA', 'Round of 16', '4-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1998, 'FIFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1998, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1998, 'FIFA', 'Final', '0-3', 'L');
INSERT INTO Competes_In VALUES('Chile', 1998, 'FIFA', 'Round of 16', '4-1', 'L');
INSERT INTO Competes_In VALUES('Colombia', 1998, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 1998, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Morocco', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Nigeria', 1994, 'FIFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Saudi Arabia', 1994, 'FIFA', 'Round of 16', '1-3', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1994, 'FIFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1994, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1994, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1994, 'FIFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1994, 'FIFA', 'Match for third place', '4-0', 'L');
INSERT INTO Competes_In VALUES('Germany', 1994, 'FIFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Germany', 1994, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Greece', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1994, 'FIFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1994, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1994, 'FIFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1994, 'FIFA', 'Final', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1994, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1994, 'FIFA', 'Quarter-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Norway', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1994, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1994, 'FIFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Romania', 1994, 'FIFA', 'Quarter-finals', '2-2', 'L');
INSERT INTO Competes_In VALUES('Russia', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1994, 'FIFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1994, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1994, 'FIFA', 'Round of 16', '1-3', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1994, 'FIFA', 'Quarter-finals', '2-2', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1994, 'FIFA', 'Semi-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1994, 'FIFA', 'Match for third place', '4-0', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 1994, 'FIFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1994, 'FIFA', 'Round of 16', '1-1', 'L');
INSERT INTO Competes_In VALUES('USA', 1994, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1994, 'FIFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('Bolivia', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1994, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1994, 'FIFA', 'Quarter-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1994, 'FIFA', 'Semi-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1994, 'FIFA', 'Final', '0-0', 'L');
INSERT INTO Competes_In VALUES('Colombia', 1994, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 1990, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Cameroon', 1990, 'FIFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Egypt', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('United Arab Emirates', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1990, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1990, 'FIFA', 'Round of 16', '4-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1990, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('England', 1990, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('England', 1990, 'FIFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('England', 1990, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('England', 1990, 'FIFA', 'Match for third place', '2-1', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1990, 'FIFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1990, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1990, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1990, 'FIFA', 'Final', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1990, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1990, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1990, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1990, 'FIFA', 'Match for third place', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1990, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1990, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1990, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1990, 'FIFA', 'Round of 16', '0-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1990, 'FIFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1990, 'FIFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1990, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Costa Rica', 1990, 'FIFA', 'Round of 16', '4-1', 'L');
INSERT INTO Competes_In VALUES('USA', 1990, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1990, 'FIFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Argentina', 1990, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1990, 'FIFA', 'Semi-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1990, 'FIFA', 'Final', '1-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1990, 'FIFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Colombia', 1990, 'FIFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1990, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Algeria', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Morocco', 1986, 'FIFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Iraq', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1986, 'FIFA', 'Round of 16', '3-4', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1986, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1986, 'FIFA', 'Semi-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1986, 'FIFA', 'Match for third place', '4-2', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1986, 'FIFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1986, 'FIFA', 'Round of 16', '1-5', 'L');
INSERT INTO Competes_In VALUES('England', 1986, 'FIFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('England', 1986, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('France', 1986, 'FIFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('France', 1986, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('France', 1986, 'FIFA', 'Semi-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('France', 1986, 'FIFA', 'Match for third place', '4-2', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1986, 'FIFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1986, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1986, 'FIFA', 'Semi-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1986, 'FIFA', 'Final', '3-2', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1986, 'FIFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('Northern Ireland', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Poland', 1986, 'FIFA', 'Round of 16', '4-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1986, 'FIFA', 'Round of 16', '3-4', 'L');
INSERT INTO Competes_In VALUES('Spain', 1986, 'FIFA', 'Round of 16', '1-5', 'W');
INSERT INTO Competes_In VALUES('Spain', 1986, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Canada', 1986, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1986, 'FIFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Mexico', 1986, 'FIFA', 'Quarter-finals', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1986, 'FIFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Argentina', 1986, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Argentina', 1986, 'FIFA', 'Semi-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Argentina', 1986, 'FIFA', 'Final', '3-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1986, 'FIFA', 'Round of 16', '4-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1986, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 1986, 'FIFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1986, 'FIFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Algeria', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Cameroon', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Kuwait', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 1982, 'FIFA', 'Semi-finals', '3-3', 'L');
INSERT INTO Competes_In VALUES('France', 1982, 'FIFA', 'Match for third place', '3-2', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1982, 'FIFA', 'Semi-finals', '3-3', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1982, 'FIFA', 'Final', '3-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1982, 'FIFA', 'Semi-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1982, 'FIFA', 'Final', '3-1', 'W');
INSERT INTO Competes_In VALUES('Northern Ireland', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Poland', 1982, 'FIFA', 'Semi-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Poland', 1982, 'FIFA', 'Match for third place', '3-2', 'W');
INSERT INTO Competes_In VALUES('Scotland', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('El Salvador', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Honduras', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('New Zealand', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Chile', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Peru', 1982, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Tunisia', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Iran', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1978, 'FIFA', 'Match for third place', '2-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1978, 'FIFA', 'Final', '3-1', 'L');
INSERT INTO Competes_In VALUES('Poland', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1978, 'FIFA', 'Final', '3-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1978, 'FIFA', 'Match for third place', '2-1', 'W');
INSERT INTO Competes_In VALUES('Peru', 1978, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Zaire', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Australia', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('German DR', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1974, 'FIFA', 'Final', '1-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1974, 'FIFA', 'Final', '1-2', 'L');
INSERT INTO Competes_In VALUES('Poland', 1974, 'FIFA', 'Match for third place', '0-1', 'W');
INSERT INTO Competes_In VALUES('Scotland', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Haiti', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1974, 'FIFA', 'Match for third place', '0-1', 'L');
INSERT INTO Competes_In VALUES('Chile', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1974, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Morocco', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 1970, 'FIFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1970, 'FIFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1970, 'FIFA', 'Semi-finals', '4-3', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1970, 'FIFA', 'Match for third place', '1-0', 'W');
INSERT INTO Competes_In VALUES('Israel', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1970, 'FIFA', 'Quarter-finals', '4-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1970, 'FIFA', 'Semi-finals', '4-3', 'W');
INSERT INTO Competes_In VALUES('Italy', 1970, 'FIFA', 'Final', '4-1', 'L');
INSERT INTO Competes_In VALUES('Romania', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1970, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('El Salvador', 1970, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1970, 'FIFA', 'Quarter-finals', '4-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1970, 'FIFA', 'Quarter-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1970, 'FIFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1970, 'FIFA', 'Final', '4-1', 'W');
INSERT INTO Competes_In VALUES('Peru', 1970, 'FIFA', 'Quarter-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1970, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Uruguay', 1970, 'FIFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1970, 'FIFA', 'Match for third place', '1-0', 'L');
INSERT INTO Competes_In VALUES('Korea DPR', 1966, 'FIFA', 'Quarter-finals', '5-3', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 1966, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('England', 1966, 'FIFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('England', 1966, 'FIFA', 'Final', '4-2', 'W');
INSERT INTO Competes_In VALUES('France', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1966, 'FIFA', 'Quarter-finals', '4-0', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1966, 'FIFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1966, 'FIFA', 'Final', '4-2', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1966, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1966, 'FIFA', 'Quarter-finals', '5-3', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1966, 'FIFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1966, 'FIFA', 'Match for third place', '2-1', 'W');
INSERT INTO Competes_In VALUES('Soviet Union', 1966, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Soviet Union', 1966, 'FIFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1966, 'FIFA', 'Match for third place', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1966, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Chile', 1966, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1966, 'FIFA', 'Quarter-finals', '4-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1962, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1962, 'FIFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1962, 'FIFA', 'Final', '3-1', 'L');
INSERT INTO Competes_In VALUES('England', 1962, 'FIFA', 'Quarter-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1962, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1962, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1962, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1962, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1962, 'FIFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1962, 'FIFA', 'Match for third place', '1-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1962, 'FIFA', 'Quarter-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1962, 'FIFA', 'Semi-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1962, 'FIFA', 'Final', '3-1', 'W');
INSERT INTO Competes_In VALUES('Chile', 1962, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Chile', 1962, 'FIFA', 'Semi-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Chile', 1962, 'FIFA', 'Match for third place', '1-0', 'W');
INSERT INTO Competes_In VALUES('Colombia', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1962, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 1958, 'FIFA', 'Quarter-finals', '4-0', 'W');
INSERT INTO Competes_In VALUES('France', 1958, 'FIFA', 'Semi-finals', '5-2', 'L');
INSERT INTO Competes_In VALUES('France', 1958, 'FIFA', 'Match for third place', '6-3', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1958, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1958, 'FIFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1958, 'FIFA', 'Match for third place', '6-3', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Northern Ireland', 1958, 'FIFA', 'Quarter-finals', '4-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Soviet Union', 1958, 'FIFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1958, 'FIFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1958, 'FIFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1958, 'FIFA', 'Final', '5-2', 'L');
INSERT INTO Competes_In VALUES('Wales', 1958, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1958, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1958, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1958, 'FIFA', 'Semi-finals', '5-2', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1958, 'FIFA', 'Final', '5-2', 'W');
INSERT INTO Competes_In VALUES('Paraguay', 1958, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Korea Republic', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1954, 'FIFA', 'Quarter-finals', '7-5', 'W');
INSERT INTO Competes_In VALUES('Austria', 1954, 'FIFA', 'Semi-finals', '6-1', 'L');
INSERT INTO Competes_In VALUES('Austria', 1954, 'FIFA', 'Match for third place', '3-1', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('England', 1954, 'FIFA', 'Quarter-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('France', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Germany FR', 1954, 'FIFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1954, 'FIFA', 'Semi-finals', '6-1', 'W');
INSERT INTO Competes_In VALUES('Germany FR', 1954, 'FIFA', 'Final', '3-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1954, 'FIFA', 'Quarter-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1954, 'FIFA', 'Semi-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1954, 'FIFA', 'Final', '3-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1954, 'FIFA', 'Quarter-finals', '7-5', 'L');
INSERT INTO Competes_In VALUES('Turkey', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1954, 'FIFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1954, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1954, 'FIFA', 'Quarter-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1954, 'FIFA', 'Quarter-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Uruguay', 1954, 'FIFA', 'Semi-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1954, 'FIFA', 'Match for third place', '3-1', 'L');
INSERT INTO Competes_In VALUES('England', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('USA', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Bolivia', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Chile', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1950, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Dutch East Indies', 1938, 'FIFA', 'First round', '6-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1938, 'FIFA', 'First round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1938, 'FIFA', 'First round', '3-0', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1938, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1938, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('France', 1938, 'FIFA', 'First round', '3-1', 'W');
INSERT INTO Competes_In VALUES('France', 1938, 'FIFA', 'Quarter-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 1938, 'FIFA', 'First round', '1-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 1938, 'FIFA', 'First round', '4-2', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1938, 'FIFA', 'First round', '6-0', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1938, 'FIFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1938, 'FIFA', 'Semi-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1938, 'FIFA', 'Final', '4-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 1938, 'FIFA', 'First round', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1938, 'FIFA', 'Quarter-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1938, 'FIFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1938, 'FIFA', 'Final', '4-2', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1938, 'FIFA', 'First round', '3-0', 'L');
INSERT INTO Competes_In VALUES('Norway', 1938, 'FIFA', 'First round', '2-1', 'L');
INSERT INTO Competes_In VALUES('Poland', 1938, 'FIFA', 'First round', '6-5', 'L');
INSERT INTO Competes_In VALUES('Romania', 1938, 'FIFA', 'First round', '3-3', 'L');
INSERT INTO Competes_In VALUES('Romania', 1938, 'FIFA', 'First round', '2-1', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1938, 'FIFA', 'Quarter-finals', '8-0', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1938, 'FIFA', 'Semi-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1938, 'FIFA', 'Match for third place', '4-2', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1938, 'FIFA', 'First round', '1-1', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1938, 'FIFA', 'First round', '4-2', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 1938, 'FIFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Cuba', 1938, 'FIFA', 'First round', '3-3', 'L');
INSERT INTO Competes_In VALUES('Cuba', 1938, 'FIFA', 'First round', '2-1', 'W');
INSERT INTO Competes_In VALUES('Cuba', 1938, 'FIFA', 'Quarter-finals', '8-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1938, 'FIFA', 'First round', '6-5', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1938, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1938, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Brazil', 1938, 'FIFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1938, 'FIFA', 'Match for third place', '4-2', 'W');
INSERT INTO Competes_In VALUES('Egypt', 1934, 'FIFA', 'Preliminary round', '4-2', 'L');
INSERT INTO Competes_In VALUES('Austria', 1934, 'FIFA', 'Preliminary round', '3-2', 'W');
INSERT INTO Competes_In VALUES('Austria', 1934, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Austria', 1934, 'FIFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Austria', 1934, 'FIFA', 'Match for third place', '3-2', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1934, 'FIFA', 'Preliminary round', '5-2', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1934, 'FIFA', 'Preliminary round', '2-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1934, 'FIFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1934, 'FIFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1934, 'FIFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('France', 1934, 'FIFA', 'Preliminary round', '3-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 1934, 'FIFA', 'Preliminary round', '5-2', 'W');
INSERT INTO Competes_In VALUES('Germany', 1934, 'FIFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 1934, 'FIFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 1934, 'FIFA', 'Match for third place', '3-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1934, 'FIFA', 'Preliminary round', '4-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1934, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1934, 'FIFA', 'Preliminary round', '7-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1934, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1934, 'FIFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1934, 'FIFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1934, 'FIFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1934, 'FIFA', 'Preliminary round', '3-2', 'L');
INSERT INTO Competes_In VALUES('Romania', 1934, 'FIFA', 'Preliminary round', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1934, 'FIFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 1934, 'FIFA', 'Quarter-finals', '1-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1934, 'FIFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1934, 'FIFA', 'Preliminary round', '3-2', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1934, 'FIFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Switzerland', 1934, 'FIFA', 'Preliminary round', '3-2', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 1934, 'FIFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('USA', 1934, 'FIFA', 'Preliminary round', '7-1', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1934, 'FIFA', 'Preliminary round', '3-2', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1934, 'FIFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('France', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1930, 'FIFA', 'Semi-finals', '6-1', 'L');
INSERT INTO Competes_In VALUES('Mexico', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('USA', 1930, 'FIFA', 'Semi-finals', '6-1', 'L');
INSERT INTO Competes_In VALUES('Argentina', 1930, 'FIFA', 'Semi-finals', '6-1', 'W');
INSERT INTO Competes_In VALUES('Argentina', 1930, 'FIFA', 'Final', '4-2', 'L');
INSERT INTO Competes_In VALUES('Bolivia', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Brazil', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Chile', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Paraguay', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Peru', 1930, 'FIFA', 'Group', '0-0', 'L');
INSERT INTO Competes_In VALUES('Uruguay', 1930, 'FIFA', 'Semi-finals', '6-1', 'W');
INSERT INTO Competes_In VALUES('Uruguay', 1930, 'FIFA', 'Final', '4-2', 'W');
