INSERT INTO Country VALUES('Algeria', 'Africa');
INSERT INTO Country VALUES('Cameroon', 'Africa');
INSERT INTO Country VALUES('Ivory Coast', 'Africa');
INSERT INTO Country VALUES('Ghana', 'Africa');
INSERT INTO Country VALUES('Nigeria', 'Africa');
INSERT INTO Country VALUES('Australia', 'Asia');
INSERT INTO Country VALUES('Iran', 'Asia');
INSERT INTO Country VALUES('Japan', 'Asia');
INSERT INTO Country VALUES('Korea Republic', 'Asia');
INSERT INTO Country VALUES('Belgium', 'Europe');
INSERT INTO Country VALUES('Bosnia and Herzegovina', 'Europe');
INSERT INTO Country VALUES('Croatia', 'Europe');
INSERT INTO Country VALUES('England', 'Europe');
INSERT INTO Country VALUES('France', 'Europe');
INSERT INTO Country VALUES('Germany', 'Europe');
INSERT INTO Country VALUES('Greece', 'Europe');
INSERT INTO Country VALUES('Italy', 'Europe');
INSERT INTO Country VALUES('Netherlands', 'Europe');
INSERT INTO Country VALUES('Portugal', 'Europe');
INSERT INTO Country VALUES('Russia', 'Europe');
INSERT INTO Country VALUES('Spain', 'Europe');
INSERT INTO Country VALUES('Switzerland', 'Europe');
INSERT INTO Country VALUES('Costa Rica', 'North/Central America');
INSERT INTO Country VALUES('Honduras', 'North/Central America');
INSERT INTO Country VALUES('Mexico', 'North/Central America');
INSERT INTO Country VALUES('USA', 'North/Central America');
INSERT INTO Country VALUES('Argentina', 'South America');
INSERT INTO Country VALUES('Brazil', 'South America');
INSERT INTO Country VALUES('Chile', 'South America');
INSERT INTO Country VALUES('Colombia', 'South America');
INSERT INTO Country VALUES('Ecuador', 'South America');
INSERT INTO Country VALUES('Uruguay', 'South America');
INSERT INTO Country VALUES('South Africa', 'Africa');
INSERT INTO Country VALUES('Korea DPR', 'Asia');
INSERT INTO Country VALUES('Denmark', 'Europe');
INSERT INTO Country VALUES('Serbia', 'Europe');
INSERT INTO Country VALUES('Slovakia', 'Europe');
INSERT INTO Country VALUES('Slovenia', 'Europe');
INSERT INTO Country VALUES('New Zealand', 'Oceania');
INSERT INTO Country VALUES('Paraguay', 'South America');
INSERT INTO Country VALUES('Angola', 'Africa');
INSERT INTO Country VALUES('Togo', 'Africa');
INSERT INTO Country VALUES('Tunisia', 'Africa');
INSERT INTO Country VALUES('Saudi Arabia', 'Asia');
INSERT INTO Country VALUES('Czech Republic', 'Europe');
INSERT INTO Country VALUES('Poland', 'Europe');
INSERT INTO Country VALUES('Serbia and Montenegro', 'Europe');
INSERT INTO Country VALUES('Sweden', 'Europe');
INSERT INTO Country VALUES('Ukraine', 'Europe');
INSERT INTO Country VALUES('Trinidad and Tobago', 'North/Central America');
INSERT INTO Country VALUES('Senegal', 'Africa');
INSERT INTO Country VALUES('China PR', 'Asia');
INSERT INTO Country VALUES('Republic of Ireland', 'Europe');
INSERT INTO Country VALUES('Turkey', 'Europe');
INSERT INTO Country VALUES('Morocco', 'Africa');
INSERT INTO Country VALUES('Austria', 'Europe');
INSERT INTO Country VALUES('Bulgaria', 'Europe');
INSERT INTO Country VALUES('Norway', 'Europe');
INSERT INTO Country VALUES('Romania', 'Europe');
INSERT INTO Country VALUES('Scotland', 'Europe');
INSERT INTO Country VALUES('Yugoslavia', 'Europe');
INSERT INTO Country VALUES('Jamaica', 'North/Central America');
INSERT INTO Country VALUES('Bolivia', 'South America');
INSERT INTO Country VALUES('Egypt', 'Africa');
INSERT INTO Country VALUES('United Arab Emirates', 'Asia');
INSERT INTO Country VALUES('Czechoslovakia', 'Europe');
INSERT INTO Country VALUES('Germany FR', 'Europe');
INSERT INTO Country VALUES('Soviet Union', 'Europe');
INSERT INTO Country VALUES('Iraq', 'Asia');
INSERT INTO Country VALUES('Hungary', 'Europe');
INSERT INTO Country VALUES('Northern Ireland', 'Europe');
INSERT INTO Country VALUES('Canada', 'North/Central America');
INSERT INTO Country VALUES('Kuwait', 'Asia');
INSERT INTO Country VALUES('El Salvador', 'North/Central America');
INSERT INTO Country VALUES('Peru', 'South America');
INSERT INTO Country VALUES('Zaire', 'Africa');
INSERT INTO Country VALUES('German DR', 'Europe');
INSERT INTO Country VALUES('Haiti', 'North/Central America');
INSERT INTO Country VALUES('Israel', 'Asia');
INSERT INTO Country VALUES('Wales', 'Europe');
INSERT INTO Country VALUES('Dutch East Indies', 'Asia');
INSERT INTO Country VALUES('Cuba', 'North/Central America');
INSERT INTO Country VALUES('Finland', 'Europe');
INSERT INTO Country VALUES('Benin', 'Africa');
INSERT INTO Country VALUES('Botswana', 'Africa');
INSERT INTO Country VALUES('Burkina Faso', 'Africa');
INSERT INTO Country VALUES('Cape Verde', 'Africa');
INSERT INTO Country VALUES('Chad', 'Africa');
INSERT INTO Country VALUES('Comoros', 'Africa');
INSERT INTO Country VALUES('Republic of the Congo', 'Africa');
INSERT INTO Country VALUES('Democratic Republic of the Congo', 'Africa');
INSERT INTO Country VALUES('Djibouti', 'Africa');
INSERT INTO Country VALUES('Eritrea', 'Africa');
INSERT INTO Country VALUES('Equatorial Guinea', 'Africa');
INSERT INTO Country VALUES('Gabon', 'Africa');
INSERT INTO Country VALUES('Gambia', 'Africa');
INSERT INTO Country VALUES('Guinea', 'Africa');
INSERT INTO Country VALUES('Kenya', 'Africa');
INSERT INTO Country VALUES('Lesotho', 'Africa');
INSERT INTO Country VALUES('Liberia', 'Africa');
INSERT INTO Country VALUES('Libya', 'Africa');
INSERT INTO Country VALUES('Madagascar', 'Africa');
INSERT INTO Country VALUES('Malawi', 'Africa');
INSERT INTO Country VALUES('Mali', 'Africa');
INSERT INTO Country VALUES('Mauritania', 'Africa');
INSERT INTO Country VALUES('Mauritius', 'Africa');
INSERT INTO Country VALUES('Mozambique', 'Africa');
INSERT INTO Country VALUES('Namibia', 'Africa');
INSERT INTO Country VALUES('Niger', 'Africa');
INSERT INTO Country VALUES('Rwanda', 'Africa');
INSERT INTO Country VALUES('Seychelles', 'Africa');
INSERT INTO Country VALUES('Sierra Leone', 'Africa');
INSERT INTO Country VALUES('Somalia', 'Africa');
INSERT INTO Country VALUES('Sudan', 'Africa');
INSERT INTO Country VALUES('Swaziland', 'Africa');
INSERT INTO Country VALUES('Uganda', 'Africa');
INSERT INTO Country VALUES('Zambia', 'Africa');
INSERT INTO Country VALUES('Zimbabwe', 'Africa');
INSERT INTO Country VALUES('Afghanistan', 'Asia');
INSERT INTO Country VALUES('Armenia', 'Asia');
INSERT INTO Country VALUES('Azerbaijan', 'Asia');
INSERT INTO Country VALUES('Bahrain', 'Asia');
INSERT INTO Country VALUES('Bangladesh', 'Asia');
INSERT INTO Country VALUES('Bhutan', 'Asia');
INSERT INTO Country VALUES('Brunei', 'Asia');
INSERT INTO Country VALUES('Cambodia', 'Asia');
INSERT INTO Country VALUES('Taiwan', 'Asia');
INSERT INTO Country VALUES('East Timor', 'Asia');
INSERT INTO Country VALUES('India', 'Asia');
INSERT INTO Country VALUES('Indonesia', 'Asia');
INSERT INTO Country VALUES('Palestine', 'Asia');
INSERT INTO Country VALUES('Jordan', 'Asia');
INSERT INTO Country VALUES('Kazakhstan', 'Asia');
INSERT INTO Country VALUES('Kyrgyzstan', 'Asia');
INSERT INTO Country VALUES('Laos', 'Asia');
INSERT INTO Country VALUES('Lebanon', 'Asia');
INSERT INTO Country VALUES('Malaysia', 'Asia');
INSERT INTO Country VALUES('Maldives', 'Asia');
INSERT INTO Country VALUES('Mongolia', 'Asia');
INSERT INTO Country VALUES('Myanmar', 'Asia');
INSERT INTO Country VALUES('Nepal', 'Asia');
INSERT INTO Country VALUES('Oman', 'Asia');
INSERT INTO Country VALUES('Pakistan', 'Asia');
INSERT INTO Country VALUES('Philippines', 'Asia');
INSERT INTO Country VALUES('Qatar', 'Asia');
INSERT INTO Country VALUES('Singapore', 'Asia');
INSERT INTO Country VALUES('Sri Lanka', 'Asia');
INSERT INTO Country VALUES('Syria', 'Asia');
INSERT INTO Country VALUES('Tajikistan', 'Asia');
INSERT INTO Country VALUES('Thailand', 'Asia');
INSERT INTO Country VALUES('Turkmenistan', 'Asia');
INSERT INTO Country VALUES('Uzbekistan', 'Asia');
INSERT INTO Country VALUES('Vietnam', 'Asia');
INSERT INTO Country VALUES('Yemen', 'Asia');
INSERT INTO Country VALUES('Albania', 'Europe');
INSERT INTO Country VALUES('Andorra', 'Europe');
INSERT INTO Country VALUES('Belarus', 'Europe');
INSERT INTO Country VALUES('Cyprus', 'Europe');
INSERT INTO Country VALUES('Estonia', 'Europe');
INSERT INTO Country VALUES('Georgia', 'Europe');
INSERT INTO Country VALUES('Iceland', 'Europe');
INSERT INTO Country VALUES('Latvia', 'Europe');
INSERT INTO Country VALUES('Liechtenstein', 'Europe');
INSERT INTO Country VALUES('Lithuania', 'Europe');
INSERT INTO Country VALUES('Luxembourg', 'Europe');
INSERT INTO Country VALUES('Malta', 'Europe');
INSERT INTO Country VALUES('Moldova', 'Europe');
INSERT INTO Country VALUES('Monaco', 'Europe');
INSERT INTO Country VALUES('San Marino', 'Europe');
INSERT INTO Country VALUES('Vatican City', 'Europe');
INSERT INTO Country VALUES('Greenland', 'North/Central America');
INSERT INTO Country VALUES('Antigua', 'North/Central America');
INSERT INTO Country VALUES('Bahamas', 'North/Central America');
INSERT INTO Country VALUES('Barbados', 'North/Central America');
INSERT INTO Country VALUES('Belize', 'North/Central America');
INSERT INTO Country VALUES('Dominica', 'North/Central America');
INSERT INTO Country VALUES('Dominican Republic', 'North/Central America');
INSERT INTO Country VALUES('Grenada', 'North/Central America');
INSERT INTO Country VALUES('Guatemala', 'North/Central America');
INSERT INTO Country VALUES('Nicaragua', 'North/Central America');
INSERT INTO Country VALUES('Panama', 'North/Central America');
INSERT INTO Country VALUES('Saint Kitts', 'North/Central America');
INSERT INTO Country VALUES('Saint Lucia', 'North/Central America');
INSERT INTO Country VALUES('Saint Vincent', 'North/Central America');
INSERT INTO Country VALUES('Turks and Caicos', 'North/Central America');
INSERT INTO Country VALUES('French Guiana', 'South America');
INSERT INTO Country VALUES('Guyana', 'South America');
INSERT INTO Country VALUES('Suriname', 'South America');
INSERT INTO Country VALUES('Venezuela', 'South America');
INSERT INTO Country VALUES('Fiji', 'Oceania');
INSERT INTO Country VALUES('Papua New Guinea', 'Oceania');
INSERT INTO Country VALUES('Solomon Islands', 'Oceania');
INSERT INTO Country VALUES('Vanuatu', 'Oceania');
INSERT INTO Country VALUES('Kiribati', 'Oceania');
INSERT INTO Country VALUES('Tuvalu', 'Oceania');
INSERT INTO Country VALUES('Samoa', 'Oceania');
INSERT INTO Country VALUES('Ireland', 'Europe');
INSERT INTO Country VALUES('USSR', 'Europe');
INSERT INTO Country VALUES('China', 'Asia');
INSERT INTO Country VALUES('West Germany', 'Europe');
INSERT INTO Country VALUES('East Germany', 'Europe');
INSERT INTO Country VALUES('Montenegro', 'Europe');
INSERT INTO Country VALUES('German Dem. Rep.', 'Europe');
INSERT INTO Country VALUES('North Korea', 'Asia');
INSERT INTO Country VALUES('South Korea', 'Asia');