INSERT INTO Country VALUES('Algeria');
INSERT INTO Country VALUES('Cameroon');
INSERT INTO Country VALUES('Ivory Coast');
INSERT INTO Country VALUES('Ghana');
INSERT INTO Country VALUES('Nigeria');
INSERT INTO Country VALUES('Australia');
INSERT INTO Country VALUES('Iran');
INSERT INTO Country VALUES('Japan');
INSERT INTO Country VALUES('Korea Republic');
INSERT INTO Country VALUES('Belgium');
INSERT INTO Country VALUES('Bosnia and Herzegovina');
INSERT INTO Country VALUES('Croatia');
INSERT INTO Country VALUES('England');
INSERT INTO Country VALUES('France');
INSERT INTO Country VALUES('Germany');
INSERT INTO Country VALUES('Greece');
INSERT INTO Country VALUES('Italy');
INSERT INTO Country VALUES('Netherlands');
INSERT INTO Country VALUES('Portugal');
INSERT INTO Country VALUES('Russia');
INSERT INTO Country VALUES('Spain');
INSERT INTO Country VALUES('Switzerland');
INSERT INTO Country VALUES('Costa Rica');
INSERT INTO Country VALUES('Honduras');
INSERT INTO Country VALUES('Mexico');
INSERT INTO Country VALUES('USA');
INSERT INTO Country VALUES('Argentina');
INSERT INTO Country VALUES('Brazil');
INSERT INTO Country VALUES('Chile');
INSERT INTO Country VALUES('Colombia');
INSERT INTO Country VALUES('Ecuador');
INSERT INTO Country VALUES('Uruguay');
INSERT INTO Country VALUES('South Africa');
INSERT INTO Country VALUES('Korea DPR');
INSERT INTO Country VALUES('Denmark');
INSERT INTO Country VALUES('Serbia');
INSERT INTO Country VALUES('Slovakia');
INSERT INTO Country VALUES('Slovenia');
INSERT INTO Country VALUES('New Zealand');
INSERT INTO Country VALUES('Paraguay');
INSERT INTO Country VALUES('Angola');
INSERT INTO Country VALUES('Togo');
INSERT INTO Country VALUES('Tunisia');
INSERT INTO Country VALUES('Saudi Arabia');
INSERT INTO Country VALUES('Czech Republic');
INSERT INTO Country VALUES('Poland');
INSERT INTO Country VALUES('Serbia and Montenegro');
INSERT INTO Country VALUES('Sweden');
INSERT INTO Country VALUES('Ukraine');
INSERT INTO Country VALUES('Trinidad and Tobago');
INSERT INTO Country VALUES('Senegal');
INSERT INTO Country VALUES('China PR');
INSERT INTO Country VALUES('Republic of Ireland');
INSERT INTO Country VALUES('Turkey');
INSERT INTO Country VALUES('Morocco');
INSERT INTO Country VALUES('Austria');
INSERT INTO Country VALUES('Bulgaria');
INSERT INTO Country VALUES('Norway');
INSERT INTO Country VALUES('Romania');
INSERT INTO Country VALUES('Scotland');
INSERT INTO Country VALUES('Yugoslavia');
INSERT INTO Country VALUES('Jamaica');
INSERT INTO Country VALUES('Bolivia');
INSERT INTO Country VALUES('Egypt');
INSERT INTO Country VALUES('United Arab Emirates');
INSERT INTO Country VALUES('Czechoslovakia');
INSERT INTO Country VALUES('Germany FR');
INSERT INTO Country VALUES('Soviet Union');
INSERT INTO Country VALUES('Iraq');
INSERT INTO Country VALUES('Hungary');
INSERT INTO Country VALUES('Northern Ireland');
INSERT INTO Country VALUES('Canada');
INSERT INTO Country VALUES('Kuwait');
INSERT INTO Country VALUES('El Salvador');
INSERT INTO Country VALUES('Peru');
INSERT INTO Country VALUES('Zaire');
INSERT INTO Country VALUES('German DR');
INSERT INTO Country VALUES('Haiti');
INSERT INTO Country VALUES('Israel');
INSERT INTO Country VALUES('Wales');
INSERT INTO Country VALUES('Dutch East Indies');
INSERT INTO Country VALUES('Cuba');
