INSERT INTO Country VALUES('Algeria', 'Africa');
INSERT INTO Country VALUES('Cameroon', 'Africa');
INSERT INTO Country VALUES('Ivory Coast', 'Africa');
INSERT INTO Country VALUES('Ghana', 'Africa');
INSERT INTO Country VALUES('Nigeria', 'Africa');
INSERT INTO Country VALUES('Australia', 'Asia');
INSERT INTO Country VALUES('Iran', 'Asia');
INSERT INTO Country VALUES('Japan', 'Asia');
INSERT INTO Country VALUES('Korea Republic', 'Asia');
INSERT INTO Country VALUES('Belgium', 'Europe');
INSERT INTO Country VALUES('Bosnia and Herzegovina', 'Europe');
INSERT INTO Country VALUES('Croatia', 'Europe');
INSERT INTO Country VALUES('England', 'Europe');
INSERT INTO Country VALUES('France', 'Europe');
INSERT INTO Country VALUES('Germany', 'Europe');
INSERT INTO Country VALUES('Greece', 'Europe');
INSERT INTO Country VALUES('Italy', 'Europe');
INSERT INTO Country VALUES('Netherlands', 'Europe');
INSERT INTO Country VALUES('Portugal', 'Europe');
INSERT INTO Country VALUES('Russia', 'Europe');
INSERT INTO Country VALUES('Spain', 'Europe');
INSERT INTO Country VALUES('Switzerland', 'Europe');
INSERT INTO Country VALUES('Costa Rica', 'North/Central America');
INSERT INTO Country VALUES('Honduras', 'North/Central America');
INSERT INTO Country VALUES('Mexico', 'North/Central America');
INSERT INTO Country VALUES('USA', 'North/Central America');
INSERT INTO Country VALUES('Argentina', 'South America');
INSERT INTO Country VALUES('Brazil', 'South America');
INSERT INTO Country VALUES('Chile', 'South America');
INSERT INTO Country VALUES('Colombia', 'South America');
INSERT INTO Country VALUES('Ecuador', 'South America');
INSERT INTO Country VALUES('Uruguay', 'South America');
INSERT INTO Country VALUES('South Africa', 'Africa');
INSERT INTO Country VALUES('Korea DPR', 'Asia');
INSERT INTO Country VALUES('Denmark', 'Europe');
INSERT INTO Country VALUES('Serbia', 'Europe');
INSERT INTO Country VALUES('Slovakia', 'Europe');
INSERT INTO Country VALUES('Slovenia', 'Europe');
INSERT INTO Country VALUES('New Zealand', 'Oceania');
INSERT INTO Country VALUES('Paraguay', 'South America');
INSERT INTO Country VALUES('Angola', 'Africa');
INSERT INTO Country VALUES('Togo', 'Africa');
INSERT INTO Country VALUES('Tunisia', 'Africa');
INSERT INTO Country VALUES('Saudi Arabia', 'Asia');
INSERT INTO Country VALUES('Czech Republic', 'Europe');
INSERT INTO Country VALUES('Poland', 'Europe');
INSERT INTO Country VALUES('Serbia and Montenegro', 'Europe');
INSERT INTO Country VALUES('Sweden', 'Europe');
INSERT INTO Country VALUES('Ukraine', 'Europe');
INSERT INTO Country VALUES('Trinidad and Tobago', 'North/Central America');
INSERT INTO Country VALUES('Senegal', 'Africa');
INSERT INTO Country VALUES('China PR', 'Asia');
INSERT INTO Country VALUES('Republic of Ireland', 'Europe');
INSERT INTO Country VALUES('Turkey', 'Europe');
INSERT INTO Country VALUES('Morocco', 'Africa');
INSERT INTO Country VALUES('Austria', 'Europe');
INSERT INTO Country VALUES('Bulgaria', 'Europe');
INSERT INTO Country VALUES('Norway', 'Europe');
INSERT INTO Country VALUES('Romania', 'Europe');
INSERT INTO Country VALUES('Scotland', 'Europe');
INSERT INTO Country VALUES('Yugoslavia', 'Europe');
INSERT INTO Country VALUES('Jamaica', 'North/Central America');
INSERT INTO Country VALUES('Bolivia', 'South America');
INSERT INTO Country VALUES('Egypt', 'Africa');
INSERT INTO Country VALUES('United Arab Emirates', 'Asia');
INSERT INTO Country VALUES('Czechoslovakia', 'Europe');
INSERT INTO Country VALUES('Germany FR', 'Europe');
INSERT INTO Country VALUES('Soviet Union', 'Europe');
INSERT INTO Country VALUES('Iraq', 'Asia');
INSERT INTO Country VALUES('Hungary', 'Europe');
INSERT INTO Country VALUES('Northern Ireland', 'Europe');
INSERT INTO Country VALUES('Canada', 'North/Central America');
INSERT INTO Country VALUES('Kuwait', 'Asia');
INSERT INTO Country VALUES('El Salvador', 'North/Central America');
INSERT INTO Country VALUES('Peru', 'South America');
INSERT INTO Country VALUES('Zaire', 'Africa');
INSERT INTO Country VALUES('German DR', 'Europe');
INSERT INTO Country VALUES('Haiti', 'North/Central America');
INSERT INTO Country VALUES('Israel', 'Asia');
INSERT INTO Country VALUES('Wales', 'Europe');
INSERT INTO Country VALUES('Dutch East Indies', 'Asia');
INSERT INTO Country VALUES('Cuba', 'North/Central America');
