INSERT INTO Has_Team VALUES('Algeria', 2014);
INSERT INTO Has_Team VALUES('Cameroon', 2014);
INSERT INTO Has_Team VALUES('Ivory Coast', 2014);
INSERT INTO Has_Team VALUES('Ghana', 2014);
INSERT INTO Has_Team VALUES('Nigeria', 2014);
INSERT INTO Has_Team VALUES('Australia', 2014);
INSERT INTO Has_Team VALUES('Iran', 2014);
INSERT INTO Has_Team VALUES('Japan', 2014);
INSERT INTO Has_Team VALUES('Korea Republic', 2014);
INSERT INTO Has_Team VALUES('Belgium', 2014);
INSERT INTO Has_Team VALUES('Bosnia and Herzegovina', 2014);
INSERT INTO Has_Team VALUES('Croatia', 2014);
INSERT INTO Has_Team VALUES('England', 2014);
INSERT INTO Has_Team VALUES('France', 2014);
INSERT INTO Has_Team VALUES('Germany', 2014);
INSERT INTO Has_Team VALUES('Greece', 2014);
INSERT INTO Has_Team VALUES('Italy', 2014);
INSERT INTO Has_Team VALUES('Netherlands', 2014);
INSERT INTO Has_Team VALUES('Portugal', 2014);
INSERT INTO Has_Team VALUES('Russia', 2014);
INSERT INTO Has_Team VALUES('Spain', 2014);
INSERT INTO Has_Team VALUES('Switzerland', 2014);
INSERT INTO Has_Team VALUES('Costa Rica', 2014);
INSERT INTO Has_Team VALUES('Honduras', 2014);
INSERT INTO Has_Team VALUES('Mexico', 2014);
INSERT INTO Has_Team VALUES('USA', 2014);
INSERT INTO Has_Team VALUES('Argentina', 2014);
INSERT INTO Has_Team VALUES('Brazil', 2014);
INSERT INTO Has_Team VALUES('Chile', 2014);
INSERT INTO Has_Team VALUES('Colombia', 2014);
INSERT INTO Has_Team VALUES('Ecuador', 2014);
INSERT INTO Has_Team VALUES('Uruguay', 2014);
INSERT INTO Has_Team VALUES('Algeria', 2010);
INSERT INTO Has_Team VALUES('Cameroon', 2010);
INSERT INTO Has_Team VALUES('Ghana', 2010);
INSERT INTO Has_Team VALUES('Ivory Coast', 2010);
INSERT INTO Has_Team VALUES('Nigeria', 2010);
INSERT INTO Has_Team VALUES('South Africa', 2010);
INSERT INTO Has_Team VALUES('Australia', 2010);
INSERT INTO Has_Team VALUES('Japan', 2010);
INSERT INTO Has_Team VALUES('Korea DPR', 2010);
INSERT INTO Has_Team VALUES('Korea Republic', 2010);
INSERT INTO Has_Team VALUES('Denmark', 2010);
INSERT INTO Has_Team VALUES('England', 2010);
INSERT INTO Has_Team VALUES('France', 2010);
INSERT INTO Has_Team VALUES('Germany', 2010);
INSERT INTO Has_Team VALUES('Greece', 2010);
INSERT INTO Has_Team VALUES('Italy', 2010);
INSERT INTO Has_Team VALUES('Netherlands', 2010);
INSERT INTO Has_Team VALUES('Portugal', 2010);
INSERT INTO Has_Team VALUES('Serbia', 2010);
INSERT INTO Has_Team VALUES('Slovakia', 2010);
INSERT INTO Has_Team VALUES('Slovenia', 2010);
INSERT INTO Has_Team VALUES('Spain', 2010);
INSERT INTO Has_Team VALUES('Switzerland', 2010);
INSERT INTO Has_Team VALUES('Honduras', 2010);
INSERT INTO Has_Team VALUES('Mexico', 2010);
INSERT INTO Has_Team VALUES('USA', 2010);
INSERT INTO Has_Team VALUES('New Zealand', 2010);
INSERT INTO Has_Team VALUES('Argentina', 2010);
INSERT INTO Has_Team VALUES('Brazil', 2010);
INSERT INTO Has_Team VALUES('Chile', 2010);
INSERT INTO Has_Team VALUES('Paraguay', 2010);
INSERT INTO Has_Team VALUES('Uruguay', 2010);
INSERT INTO Has_Team VALUES('Angola', 2006);
INSERT INTO Has_Team VALUES('Ghana', 2006);
INSERT INTO Has_Team VALUES('Ivory Coast', 2006);
INSERT INTO Has_Team VALUES('Togo', 2006);
INSERT INTO Has_Team VALUES('Tunisia', 2006);
INSERT INTO Has_Team VALUES('Australia', 2006);
INSERT INTO Has_Team VALUES('Iran', 2006);
INSERT INTO Has_Team VALUES('Japan', 2006);
INSERT INTO Has_Team VALUES('Korea Republic', 2006);
INSERT INTO Has_Team VALUES('Saudi Arabia', 2006);
INSERT INTO Has_Team VALUES('Croatia', 2006);
INSERT INTO Has_Team VALUES('Czech Republic', 2006);
INSERT INTO Has_Team VALUES('England', 2006);
INSERT INTO Has_Team VALUES('France', 2006);
INSERT INTO Has_Team VALUES('Germany', 2006);
INSERT INTO Has_Team VALUES('Italy', 2006);
INSERT INTO Has_Team VALUES('Netherlands', 2006);
INSERT INTO Has_Team VALUES('Poland', 2006);
INSERT INTO Has_Team VALUES('Portugal', 2006);
INSERT INTO Has_Team VALUES('Serbia and Montenegro', 2006);
INSERT INTO Has_Team VALUES('Spain', 2006);
INSERT INTO Has_Team VALUES('Sweden', 2006);
INSERT INTO Has_Team VALUES('Switzerland', 2006);
INSERT INTO Has_Team VALUES('Ukraine', 2006);
INSERT INTO Has_Team VALUES('Costa Rica', 2006);
INSERT INTO Has_Team VALUES('Mexico', 2006);
INSERT INTO Has_Team VALUES('Trinidad and Tobago', 2006);
INSERT INTO Has_Team VALUES('USA', 2006);
INSERT INTO Has_Team VALUES('Argentina', 2006);
INSERT INTO Has_Team VALUES('Brazil', 2006);
INSERT INTO Has_Team VALUES('Ecuador', 2006);
INSERT INTO Has_Team VALUES('Paraguay', 2006);
INSERT INTO Has_Team VALUES('Cameroon', 2002);
INSERT INTO Has_Team VALUES('Nigeria', 2002);
INSERT INTO Has_Team VALUES('Senegal', 2002);
INSERT INTO Has_Team VALUES('South Africa', 2002);
INSERT INTO Has_Team VALUES('Tunisia', 2002);
INSERT INTO Has_Team VALUES('China PR', 2002);
INSERT INTO Has_Team VALUES('Japan', 2002);
INSERT INTO Has_Team VALUES('Korea Republic', 2002);
INSERT INTO Has_Team VALUES('Saudi Arabia', 2002);
INSERT INTO Has_Team VALUES('Belgium', 2002);
INSERT INTO Has_Team VALUES('Croatia', 2002);
INSERT INTO Has_Team VALUES('Denmark', 2002);
INSERT INTO Has_Team VALUES('England', 2002);
INSERT INTO Has_Team VALUES('France', 2002);
INSERT INTO Has_Team VALUES('Germany', 2002);
INSERT INTO Has_Team VALUES('Italy', 2002);
INSERT INTO Has_Team VALUES('Poland', 2002);
INSERT INTO Has_Team VALUES('Portugal', 2002);
INSERT INTO Has_Team VALUES('Republic of Ireland', 2002);
INSERT INTO Has_Team VALUES('Russia', 2002);
INSERT INTO Has_Team VALUES('Slovenia', 2002);
INSERT INTO Has_Team VALUES('Spain', 2002);
INSERT INTO Has_Team VALUES('Sweden', 2002);
INSERT INTO Has_Team VALUES('Turkey', 2002);
INSERT INTO Has_Team VALUES('Costa Rica', 2002);
INSERT INTO Has_Team VALUES('Mexico', 2002);
INSERT INTO Has_Team VALUES('USA', 2002);
INSERT INTO Has_Team VALUES('Argentina', 2002);
INSERT INTO Has_Team VALUES('Brazil', 2002);
INSERT INTO Has_Team VALUES('Ecuador', 2002);
INSERT INTO Has_Team VALUES('Paraguay', 2002);
INSERT INTO Has_Team VALUES('Uruguay', 2002);
INSERT INTO Has_Team VALUES('Cameroon', 1998);
INSERT INTO Has_Team VALUES('Morocco', 1998);
INSERT INTO Has_Team VALUES('Nigeria', 1998);
INSERT INTO Has_Team VALUES('South Africa', 1998);
INSERT INTO Has_Team VALUES('Tunisia', 1998);
INSERT INTO Has_Team VALUES('Iran', 1998);
INSERT INTO Has_Team VALUES('Japan', 1998);
INSERT INTO Has_Team VALUES('Korea Republic', 1998);
INSERT INTO Has_Team VALUES('Saudi Arabia', 1998);
INSERT INTO Has_Team VALUES('Austria', 1998);
INSERT INTO Has_Team VALUES('Belgium', 1998);
INSERT INTO Has_Team VALUES('Bulgaria', 1998);
INSERT INTO Has_Team VALUES('Croatia', 1998);
INSERT INTO Has_Team VALUES('Denmark', 1998);
INSERT INTO Has_Team VALUES('England', 1998);
INSERT INTO Has_Team VALUES('France', 1998);
INSERT INTO Has_Team VALUES('Germany', 1998);
INSERT INTO Has_Team VALUES('Italy', 1998);
INSERT INTO Has_Team VALUES('Netherlands', 1998);
INSERT INTO Has_Team VALUES('Norway', 1998);
INSERT INTO Has_Team VALUES('Romania', 1998);
INSERT INTO Has_Team VALUES('Scotland', 1998);
INSERT INTO Has_Team VALUES('Spain', 1998);
INSERT INTO Has_Team VALUES('Yugoslavia', 1998);
INSERT INTO Has_Team VALUES('Jamaica', 1998);
INSERT INTO Has_Team VALUES('Mexico', 1998);
INSERT INTO Has_Team VALUES('USA', 1998);
INSERT INTO Has_Team VALUES('Argentina', 1998);
INSERT INTO Has_Team VALUES('Brazil', 1998);
INSERT INTO Has_Team VALUES('Chile', 1998);
INSERT INTO Has_Team VALUES('Colombia', 1998);
INSERT INTO Has_Team VALUES('Paraguay', 1998);
INSERT INTO Has_Team VALUES('Cameroon', 1994);
INSERT INTO Has_Team VALUES('Morocco', 1994);
INSERT INTO Has_Team VALUES('Nigeria', 1994);
INSERT INTO Has_Team VALUES('Korea Republic', 1994);
INSERT INTO Has_Team VALUES('Saudi Arabia', 1994);
INSERT INTO Has_Team VALUES('Belgium', 1994);
INSERT INTO Has_Team VALUES('Bulgaria', 1994);
INSERT INTO Has_Team VALUES('Germany', 1994);
INSERT INTO Has_Team VALUES('Greece', 1994);
INSERT INTO Has_Team VALUES('Italy', 1994);
INSERT INTO Has_Team VALUES('Netherlands', 1994);
INSERT INTO Has_Team VALUES('Norway', 1994);
INSERT INTO Has_Team VALUES('Republic of Ireland', 1994);
INSERT INTO Has_Team VALUES('Romania', 1994);
INSERT INTO Has_Team VALUES('Russia', 1994);
INSERT INTO Has_Team VALUES('Spain', 1994);
INSERT INTO Has_Team VALUES('Sweden', 1994);
INSERT INTO Has_Team VALUES('Switzerland', 1994);
INSERT INTO Has_Team VALUES('Mexico', 1994);
INSERT INTO Has_Team VALUES('USA', 1994);
INSERT INTO Has_Team VALUES('Argentina', 1994);
INSERT INTO Has_Team VALUES('Bolivia', 1994);
INSERT INTO Has_Team VALUES('Brazil', 1994);
INSERT INTO Has_Team VALUES('Colombia', 1994);
INSERT INTO Has_Team VALUES('Cameroon', 1990);
INSERT INTO Has_Team VALUES('Egypt', 1990);
INSERT INTO Has_Team VALUES('Korea Republic', 1990);
INSERT INTO Has_Team VALUES('United Arab Emirates', 1990);
INSERT INTO Has_Team VALUES('Austria', 1990);
INSERT INTO Has_Team VALUES('Belgium', 1990);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1990);
INSERT INTO Has_Team VALUES('England', 1990);
INSERT INTO Has_Team VALUES('Germany FR', 1990);
INSERT INTO Has_Team VALUES('Italy', 1990);
INSERT INTO Has_Team VALUES('Netherlands', 1990);
INSERT INTO Has_Team VALUES('Republic of Ireland', 1990);
INSERT INTO Has_Team VALUES('Romania', 1990);
INSERT INTO Has_Team VALUES('Scotland', 1990);
INSERT INTO Has_Team VALUES('Soviet Union', 1990);
INSERT INTO Has_Team VALUES('Spain', 1990);
INSERT INTO Has_Team VALUES('Sweden', 1990);
INSERT INTO Has_Team VALUES('Yugoslavia', 1990);
INSERT INTO Has_Team VALUES('Costa Rica', 1990);
INSERT INTO Has_Team VALUES('USA', 1990);
INSERT INTO Has_Team VALUES('Argentina', 1990);
INSERT INTO Has_Team VALUES('Brazil', 1990);
INSERT INTO Has_Team VALUES('Colombia', 1990);
INSERT INTO Has_Team VALUES('Uruguay', 1990);
INSERT INTO Has_Team VALUES('Algeria', 1986);
INSERT INTO Has_Team VALUES('Morocco', 1986);
INSERT INTO Has_Team VALUES('Iraq', 1986);
INSERT INTO Has_Team VALUES('Korea Republic', 1986);
INSERT INTO Has_Team VALUES('Belgium', 1986);
INSERT INTO Has_Team VALUES('Bulgaria', 1986);
INSERT INTO Has_Team VALUES('Denmark', 1986);
INSERT INTO Has_Team VALUES('England', 1986);
INSERT INTO Has_Team VALUES('France', 1986);
INSERT INTO Has_Team VALUES('Germany FR', 1986);
INSERT INTO Has_Team VALUES('Hungary', 1986);
INSERT INTO Has_Team VALUES('Italy', 1986);
INSERT INTO Has_Team VALUES('Northern Ireland', 1986);
INSERT INTO Has_Team VALUES('Poland', 1986);
INSERT INTO Has_Team VALUES('Portugal', 1986);
INSERT INTO Has_Team VALUES('Scotland', 1986);
INSERT INTO Has_Team VALUES('Soviet Union', 1986);
INSERT INTO Has_Team VALUES('Spain', 1986);
INSERT INTO Has_Team VALUES('Canada', 1986);
INSERT INTO Has_Team VALUES('Mexico', 1986);
INSERT INTO Has_Team VALUES('Argentina', 1986);
INSERT INTO Has_Team VALUES('Brazil', 1986);
INSERT INTO Has_Team VALUES('Paraguay', 1986);
INSERT INTO Has_Team VALUES('Uruguay', 1986);
INSERT INTO Has_Team VALUES('Algeria', 1982);
INSERT INTO Has_Team VALUES('Cameroon', 1982);
INSERT INTO Has_Team VALUES('Kuwait', 1982);
INSERT INTO Has_Team VALUES('Austria', 1982);
INSERT INTO Has_Team VALUES('Belgium', 1982);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1982);
INSERT INTO Has_Team VALUES('England', 1982);
INSERT INTO Has_Team VALUES('France', 1982);
INSERT INTO Has_Team VALUES('Germany FR', 1982);
INSERT INTO Has_Team VALUES('Hungary', 1982);
INSERT INTO Has_Team VALUES('Italy', 1982);
INSERT INTO Has_Team VALUES('Northern Ireland', 1982);
INSERT INTO Has_Team VALUES('Poland', 1982);
INSERT INTO Has_Team VALUES('Scotland', 1982);
INSERT INTO Has_Team VALUES('Soviet Union', 1982);
INSERT INTO Has_Team VALUES('Spain', 1982);
INSERT INTO Has_Team VALUES('Yugoslavia', 1982);
INSERT INTO Has_Team VALUES('El Salvador', 1982);
INSERT INTO Has_Team VALUES('Honduras', 1982);
INSERT INTO Has_Team VALUES('New Zealand', 1982);
INSERT INTO Has_Team VALUES('Argentina', 1982);
INSERT INTO Has_Team VALUES('Brazil', 1982);
INSERT INTO Has_Team VALUES('Chile', 1982);
INSERT INTO Has_Team VALUES('Peru', 1982);
INSERT INTO Has_Team VALUES('Tunisia', 1978);
INSERT INTO Has_Team VALUES('Iran', 1978);
INSERT INTO Has_Team VALUES('Austria', 1978);
INSERT INTO Has_Team VALUES('France', 1978);
INSERT INTO Has_Team VALUES('Germany FR', 1978);
INSERT INTO Has_Team VALUES('Hungary', 1978);
INSERT INTO Has_Team VALUES('Italy', 1978);
INSERT INTO Has_Team VALUES('Netherlands', 1978);
INSERT INTO Has_Team VALUES('Poland', 1978);
INSERT INTO Has_Team VALUES('Scotland', 1978);
INSERT INTO Has_Team VALUES('Spain', 1978);
INSERT INTO Has_Team VALUES('Sweden', 1978);
INSERT INTO Has_Team VALUES('Mexico', 1978);
INSERT INTO Has_Team VALUES('Argentina', 1978);
INSERT INTO Has_Team VALUES('Brazil', 1978);
INSERT INTO Has_Team VALUES('Peru', 1978);
INSERT INTO Has_Team VALUES('Zaire', 1974);
INSERT INTO Has_Team VALUES('Australia', 1974);
INSERT INTO Has_Team VALUES('Bulgaria', 1974);
INSERT INTO Has_Team VALUES('German DR', 1974);
INSERT INTO Has_Team VALUES('Germany FR', 1974);
INSERT INTO Has_Team VALUES('Italy', 1974);
INSERT INTO Has_Team VALUES('Netherlands', 1974);
INSERT INTO Has_Team VALUES('Poland', 1974);
INSERT INTO Has_Team VALUES('Scotland', 1974);
INSERT INTO Has_Team VALUES('Sweden', 1974);
INSERT INTO Has_Team VALUES('Yugoslavia', 1974);
INSERT INTO Has_Team VALUES('Haiti', 1974);
INSERT INTO Has_Team VALUES('Argentina', 1974);
INSERT INTO Has_Team VALUES('Brazil', 1974);
INSERT INTO Has_Team VALUES('Chile', 1974);
INSERT INTO Has_Team VALUES('Uruguay', 1974);
INSERT INTO Has_Team VALUES('Morocco', 1970);
INSERT INTO Has_Team VALUES('Belgium', 1970);
INSERT INTO Has_Team VALUES('Bulgaria', 1970);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1970);
INSERT INTO Has_Team VALUES('England', 1970);
INSERT INTO Has_Team VALUES('Germany FR', 1970);
INSERT INTO Has_Team VALUES('Israel', 1970);
INSERT INTO Has_Team VALUES('Italy', 1970);
INSERT INTO Has_Team VALUES('Romania', 1970);
INSERT INTO Has_Team VALUES('Soviet Union', 1970);
INSERT INTO Has_Team VALUES('Sweden', 1970);
INSERT INTO Has_Team VALUES('El Salvador', 1970);
INSERT INTO Has_Team VALUES('Mexico', 1970);
INSERT INTO Has_Team VALUES('Brazil', 1970);
INSERT INTO Has_Team VALUES('Peru', 1970);
INSERT INTO Has_Team VALUES('Uruguay', 1970);
INSERT INTO Has_Team VALUES('Korea DPR', 1966);
INSERT INTO Has_Team VALUES('Bulgaria', 1966);
INSERT INTO Has_Team VALUES('England', 1966);
INSERT INTO Has_Team VALUES('France', 1966);
INSERT INTO Has_Team VALUES('Germany FR', 1966);
INSERT INTO Has_Team VALUES('Hungary', 1966);
INSERT INTO Has_Team VALUES('Italy', 1966);
INSERT INTO Has_Team VALUES('Portugal', 1966);
INSERT INTO Has_Team VALUES('Soviet Union', 1966);
INSERT INTO Has_Team VALUES('Spain', 1966);
INSERT INTO Has_Team VALUES('Switzerland', 1966);
INSERT INTO Has_Team VALUES('Mexico', 1966);
INSERT INTO Has_Team VALUES('Argentina', 1966);
INSERT INTO Has_Team VALUES('Brazil', 1966);
INSERT INTO Has_Team VALUES('Chile', 1966);
INSERT INTO Has_Team VALUES('Uruguay', 1966);
INSERT INTO Has_Team VALUES('Bulgaria', 1962);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1962);
INSERT INTO Has_Team VALUES('England', 1962);
INSERT INTO Has_Team VALUES('Germany FR', 1962);
INSERT INTO Has_Team VALUES('Hungary', 1962);
INSERT INTO Has_Team VALUES('Italy', 1962);
INSERT INTO Has_Team VALUES('Soviet Union', 1962);
INSERT INTO Has_Team VALUES('Spain', 1962);
INSERT INTO Has_Team VALUES('Switzerland', 1962);
INSERT INTO Has_Team VALUES('Yugoslavia', 1962);
INSERT INTO Has_Team VALUES('Mexico', 1962);
INSERT INTO Has_Team VALUES('Argentina', 1962);
INSERT INTO Has_Team VALUES('Brazil', 1962);
INSERT INTO Has_Team VALUES('Chile', 1962);
INSERT INTO Has_Team VALUES('Colombia', 1962);
INSERT INTO Has_Team VALUES('Uruguay', 1962);
INSERT INTO Has_Team VALUES('Austria', 1958);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1958);
INSERT INTO Has_Team VALUES('England', 1958);
INSERT INTO Has_Team VALUES('France', 1958);
INSERT INTO Has_Team VALUES('Germany FR', 1958);
INSERT INTO Has_Team VALUES('Hungary', 1958);
INSERT INTO Has_Team VALUES('Northern Ireland', 1958);
INSERT INTO Has_Team VALUES('Scotland', 1958);
INSERT INTO Has_Team VALUES('Soviet Union', 1958);
INSERT INTO Has_Team VALUES('Sweden', 1958);
INSERT INTO Has_Team VALUES('Wales', 1958);
INSERT INTO Has_Team VALUES('Yugoslavia', 1958);
INSERT INTO Has_Team VALUES('Mexico', 1958);
INSERT INTO Has_Team VALUES('Argentina', 1958);
INSERT INTO Has_Team VALUES('Brazil', 1958);
INSERT INTO Has_Team VALUES('Paraguay', 1958);
INSERT INTO Has_Team VALUES('Korea Republic', 1954);
INSERT INTO Has_Team VALUES('Austria', 1954);
INSERT INTO Has_Team VALUES('Belgium', 1954);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1954);
INSERT INTO Has_Team VALUES('England', 1954);
INSERT INTO Has_Team VALUES('France', 1954);
INSERT INTO Has_Team VALUES('Germany FR', 1954);
INSERT INTO Has_Team VALUES('Hungary', 1954);
INSERT INTO Has_Team VALUES('Italy', 1954);
INSERT INTO Has_Team VALUES('Scotland', 1954);
INSERT INTO Has_Team VALUES('Switzerland', 1954);
INSERT INTO Has_Team VALUES('Turkey', 1954);
INSERT INTO Has_Team VALUES('Yugoslavia', 1954);
INSERT INTO Has_Team VALUES('Mexico', 1954);
INSERT INTO Has_Team VALUES('Brazil', 1954);
INSERT INTO Has_Team VALUES('Uruguay', 1954);
INSERT INTO Has_Team VALUES('England', 1950);
INSERT INTO Has_Team VALUES('Italy', 1950);
INSERT INTO Has_Team VALUES('Spain', 1950);
INSERT INTO Has_Team VALUES('Sweden', 1950);
INSERT INTO Has_Team VALUES('Switzerland', 1950);
INSERT INTO Has_Team VALUES('Yugoslavia', 1950);
INSERT INTO Has_Team VALUES('Mexico', 1950);
INSERT INTO Has_Team VALUES('USA', 1950);
INSERT INTO Has_Team VALUES('Bolivia', 1950);
INSERT INTO Has_Team VALUES('Brazil', 1950);
INSERT INTO Has_Team VALUES('Chile', 1950);
INSERT INTO Has_Team VALUES('Paraguay', 1950);
INSERT INTO Has_Team VALUES('Uruguay', 1950);
INSERT INTO Has_Team VALUES('Dutch East Indies', 1938);
INSERT INTO Has_Team VALUES('Belgium', 1938);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1938);
INSERT INTO Has_Team VALUES('France', 1938);
INSERT INTO Has_Team VALUES('Germany', 1938);
INSERT INTO Has_Team VALUES('Hungary', 1938);
INSERT INTO Has_Team VALUES('Italy', 1938);
INSERT INTO Has_Team VALUES('Netherlands', 1938);
INSERT INTO Has_Team VALUES('Norway', 1938);
INSERT INTO Has_Team VALUES('Poland', 1938);
INSERT INTO Has_Team VALUES('Romania', 1938);
INSERT INTO Has_Team VALUES('Sweden', 1938);
INSERT INTO Has_Team VALUES('Switzerland', 1938);
INSERT INTO Has_Team VALUES('Cuba', 1938);
INSERT INTO Has_Team VALUES('Brazil', 1938);
INSERT INTO Has_Team VALUES('Egypt', 1934);
INSERT INTO Has_Team VALUES('Austria', 1934);
INSERT INTO Has_Team VALUES('Belgium', 1934);
INSERT INTO Has_Team VALUES('Czechoslovakia', 1934);
INSERT INTO Has_Team VALUES('France', 1934);
INSERT INTO Has_Team VALUES('Germany', 1934);
INSERT INTO Has_Team VALUES('Hungary', 1934);
INSERT INTO Has_Team VALUES('Italy', 1934);
INSERT INTO Has_Team VALUES('Netherlands', 1934);
INSERT INTO Has_Team VALUES('Romania', 1934);
INSERT INTO Has_Team VALUES('Spain', 1934);
INSERT INTO Has_Team VALUES('Sweden', 1934);
INSERT INTO Has_Team VALUES('Switzerland', 1934);
INSERT INTO Has_Team VALUES('USA', 1934);
INSERT INTO Has_Team VALUES('Argentina', 1934);
INSERT INTO Has_Team VALUES('Brazil', 1934);
INSERT INTO Has_Team VALUES('Belgium', 1930);
INSERT INTO Has_Team VALUES('France', 1930);
INSERT INTO Has_Team VALUES('Romania', 1930);
INSERT INTO Has_Team VALUES('Yugoslavia', 1930);
INSERT INTO Has_Team VALUES('Mexico', 1930);
INSERT INTO Has_Team VALUES('USA', 1930);
INSERT INTO Has_Team VALUES('Argentina', 1930);
INSERT INTO Has_Team VALUES('Bolivia', 1930);
INSERT INTO Has_Team VALUES('Brazil', 1930);
INSERT INTO Has_Team VALUES('Chile', 1930);
INSERT INTO Has_Team VALUES('Paraguay', 1930);
INSERT INTO Has_Team VALUES('Peru', 1930);
INSERT INTO Has_Team VALUES('Uruguay', 1930);
