INSERT INTO Competes_In VALUES('Norway', 1959, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Round of 16', '5-2', 'W');
INSERT INTO Competes_In VALUES('Norway', 1959, 'UEFA', 'Round of 16', '5-2', 'L');
INSERT INTO Competes_In VALUES('France', 1959, 'UEFA', 'Quarter-finals', '5-2', 'W');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Quarter-finals', '5-2', 'L');
INSERT INTO Competes_In VALUES('Austria', 1960, 'UEFA', 'Quarter-finals', '2-4', 'L');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Quarter-finals', '2-4', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1959, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1959, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Round of 16', '5-1', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1959, 'UEFA', 'Round of 16', '5-1', 'L');
INSERT INTO Competes_In VALUES('Romania', 1960, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1960, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('USSR', 1960, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Third place', '2-0', 'W');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Third place', '2-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Round of 16', '5-1', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1959, 'UEFA', 'Round of 16', '5-1', 'L');
INSERT INTO Competes_In VALUES('France', 1958, 'UEFA', 'Round of 16', '7-1', 'W');
INSERT INTO Competes_In VALUES('Greece', 1958, 'UEFA', 'Round of 16', '7-1', 'L');
INSERT INTO Competes_In VALUES('France', 1959, 'UEFA', 'Quarter-finals', '5-2', 'W');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Quarter-finals', '5-2', 'L');
INSERT INTO Competes_In VALUES('Austria', 1960, 'UEFA', 'Quarter-finals', '2-4', 'L');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Quarter-finals', '2-4', 'W');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Semi-finals', '4-5', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Semi-finals', '4-5', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Third place', '2-0', 'W');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Third place', '2-0', 'L');
INSERT INTO Competes_In VALUES('France', 1958, 'UEFA', 'Round of 16', '7-1', 'W');
INSERT INTO Competes_In VALUES('Greece', 1958, 'UEFA', 'Round of 16', '7-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1958, 'UEFA', 'Round of 16', '3-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1958, 'UEFA', 'Round of 16', '3-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1959, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1959, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Norway', 1959, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Austria', 1959, 'UEFA', 'Round of 16', '5-2', 'W');
INSERT INTO Competes_In VALUES('Norway', 1959, 'UEFA', 'Round of 16', '5-2', 'L');
INSERT INTO Competes_In VALUES('Poland', 1959, 'UEFA', 'Round of 16', '2-4', 'L');
INSERT INTO Competes_In VALUES('Spain', 1959, 'UEFA', 'Round of 16', '2-4', 'W');
INSERT INTO Competes_In VALUES('Spain', 1959, 'UEFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Poland', 1959, 'UEFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1960, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1960, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Romania', 1958, 'UEFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 1958, 'UEFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 1959, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1959, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1960, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1960, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Poland', 1959, 'UEFA', 'Round of 16', '2-4', 'L');
INSERT INTO Competes_In VALUES('Spain', 1959, 'UEFA', 'Round of 16', '2-4', 'W');
INSERT INTO Competes_In VALUES('Spain', 1959, 'UEFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Poland', 1959, 'UEFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1958, 'UEFA', 'Round of 16', '3-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 1958, 'UEFA', 'Round of 16', '3-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 1959, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1959, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1958, 'UEFA', 'Round of 16', '3-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1958, 'UEFA', 'Round of 16', '3-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1959, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1959, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1960, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('USSR', 1960, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('USSR', 1960, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1959, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1959, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1960, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1960, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('France', 1960, 'UEFA', 'Semi-finals', '4-5', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Semi-finals', '4-5', 'W');
INSERT INTO Competes_In VALUES('USSR', 1960, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1960, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Round of 16', '4-0', 'W');
INSERT INTO Competes_In VALUES('Albania', 1963, 'UEFA', 'Round of 16', '4-0', 'L');
INSERT INTO Competes_In VALUES('Albania', 1963, 'UEFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1962, 'UEFA', 'Preliminary round', '3-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1962, 'UEFA', 'Preliminary round', '3-2', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1963, 'UEFA', 'Preliminary round', '0-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1963, 'UEFA', 'Preliminary round', '0-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1963, 'UEFA', 'Preliminary round', '1-0', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1963, 'UEFA', 'Preliminary round', '1-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1963, 'UEFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Round of 16', '3-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1963, 'UEFA', 'Round of 16', '3-1', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1962, 'UEFA', 'Preliminary round', '6-1', 'W');
INSERT INTO Competes_In VALUES('Malta', 1962, 'UEFA', 'Preliminary round', '6-1', 'L');
INSERT INTO Competes_In VALUES('Malta', 1962, 'UEFA', 'Preliminary round', '1-3', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1962, 'UEFA', 'Preliminary round', '1-3', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Round of 16', '4-0', 'W');
INSERT INTO Competes_In VALUES('Albania', 1963, 'UEFA', 'Round of 16', '4-0', 'L');
INSERT INTO Competes_In VALUES('Albania', 1963, 'UEFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Luxembourg', 1963, 'UEFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1964, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Third place', '3-1', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1964, 'UEFA', 'Third place', '3-1', 'L');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Preliminary round', '5-2', 'W');
INSERT INTO Competes_In VALUES('England', 1963, 'UEFA', 'Preliminary round', '5-2', 'L');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Preliminary round', '5-2', 'W');
INSERT INTO Competes_In VALUES('England', 1963, 'UEFA', 'Preliminary round', '5-2', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1963, 'UEFA', 'Round of 16', '1-0', 'W');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Round of 16', '1-0', 'L');
INSERT INTO Competes_In VALUES('France', 1963, 'UEFA', 'Round of 16', '3-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1963, 'UEFA', 'Round of 16', '3-1', 'L');
INSERT INTO Competes_In VALUES('France', 1964, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('France', 1964, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Wales', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('France', 1964, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('France', 1964, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Third place', '3-1', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1964, 'UEFA', 'Third place', '3-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1962, 'UEFA', 'Preliminary round', '6-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 1962, 'UEFA', 'Preliminary round', '6-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 1963, 'UEFA', 'Preliminary round', '0-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1963, 'UEFA', 'Preliminary round', '0-1', 'W');
INSERT INTO Competes_In VALUES('USSR', 1963, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1963, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('Luxembourg', 1963, 'UEFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1963, 'UEFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1963, 'UEFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Luxembourg', 1963, 'UEFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1962, 'UEFA', 'Preliminary round', '6-1', 'W');
INSERT INTO Competes_In VALUES('Malta', 1962, 'UEFA', 'Preliminary round', '6-1', 'L');
INSERT INTO Competes_In VALUES('Malta', 1962, 'UEFA', 'Preliminary round', '1-3', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1962, 'UEFA', 'Preliminary round', '1-3', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Luxembourg', 1963, 'UEFA', 'Round of 16', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1963, 'UEFA', 'Round of 16', '2-1', 'L');
INSERT INTO Competes_In VALUES('Norway', 1962, 'UEFA', 'Preliminary round', '0-2', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1962, 'UEFA', 'Preliminary round', '0-2', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1962, 'UEFA', 'Preliminary round', '6-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1962, 'UEFA', 'Preliminary round', '6-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1962, 'UEFA', 'Preliminary round', '6-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 1962, 'UEFA', 'Preliminary round', '6-0', 'L');
INSERT INTO Competes_In VALUES('Romania', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1964, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Norway', 1962, 'UEFA', 'Preliminary round', '0-2', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1962, 'UEFA', 'Preliminary round', '0-2', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1963, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1963, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Quarter-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1964, 'UEFA', 'Quarter-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Switzerland', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1962, 'UEFA', 'Preliminary round', '6-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 1962, 'UEFA', 'Preliminary round', '6-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 1963, 'UEFA', 'Preliminary round', '0-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 1963, 'UEFA', 'Preliminary round', '0-1', 'W');
INSERT INTO Competes_In VALUES('USSR', 1963, 'UEFA', 'Round of 16', '2-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1963, 'UEFA', 'Round of 16', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Quarter-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1964, 'UEFA', 'Quarter-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1964, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('USSR', 1964, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1962, 'UEFA', 'Preliminary round', '3-1', 'W');
INSERT INTO Competes_In VALUES('Wales', 1962, 'UEFA', 'Preliminary round', '3-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1962, 'UEFA', 'Preliminary round', '3-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1962, 'UEFA', 'Preliminary round', '3-2', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1963, 'UEFA', 'Preliminary round', '0-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1963, 'UEFA', 'Preliminary round', '0-1', 'W');
INSERT INTO Competes_In VALUES('Sweden', 1963, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1963, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1968, 'UEFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1968, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1968, 'UEFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1968, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Third place', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Third place', '2-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('France', 1968, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1968, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1968, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Bulgaria', 1968, 'UEFA', 'Quarter-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Quarter-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Bulgaria', 1968, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1968, 'UEFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 1968, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1968, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1968, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Third place', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1968, 'UEFA', 'Third place', '2-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('France', 1968, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('England', 1968, 'UEFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 1968, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1968, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1972, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Third place', '1-2', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Third place', '1-2', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Replay', '2-1', 'W');
INSERT INTO Competes_In VALUES('Romania', 1972, 'UEFA', 'Replay', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Semi-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1972, 'UEFA', 'Semi-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Third place', '1-2', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Third place', '1-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 1972, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Replay', '2-1', 'W');
INSERT INTO Competes_In VALUES('Romania', 1972, 'UEFA', 'Replay', '2-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1972, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1972, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1972, 'UEFA', 'Semi-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('USSR', 1972, 'UEFA', 'Semi-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('USSR', 1972, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1972, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Quarter-finals', '5-0', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1976, 'UEFA', 'Quarter-finals', '5-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1976, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1976, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1976, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1976, 'UEFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Quarter-finals', '5-0', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1976, 'UEFA', 'Quarter-finals', '5-0', 'L');
INSERT INTO Competes_In VALUES('Belgium', 1976, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1976, 'UEFA', 'Semi-finals', '3-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Semi-finals', '3-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Third place', '3-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1976, 'UEFA', 'Third place', '3-2', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1976, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('USSR', 1976, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1976, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Wales', 1976, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1976, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Wales', 1976, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1976, 'UEFA', 'Third place', '3-2', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 1976, 'UEFA', 'Third place', '3-2', 'L');
INSERT INTO Competes_In VALUES('France', 1984, 'UEFA', 'Semi-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1984, 'UEFA', 'Semi-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('France', 1984, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1984, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('France', 1984, 'UEFA', 'Semi-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1984, 'UEFA', 'Semi-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('France', 1984, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1984, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1988, 'UEFA', 'Semi-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1988, 'UEFA', 'Semi-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1988, 'UEFA', 'Final', '0-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1988, 'UEFA', 'Final', '0-2', 'W');
INSERT INTO Competes_In VALUES('USSR', 1988, 'UEFA', 'Semi-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 1988, 'UEFA', 'Semi-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('USSR', 1988, 'UEFA', 'Final', '0-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1988, 'UEFA', 'Final', '0-2', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1992, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 1992, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1992, 'UEFA', 'Semi-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Germany', 1992, 'UEFA', 'Semi-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1992, 'UEFA', 'Final', '2-0', 'W');
INSERT INTO Competes_In VALUES('Germany', 1992, 'UEFA', 'Final', '2-0', 'L');
INSERT INTO Competes_In VALUES('Sweden', 1992, 'UEFA', 'Semi-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Germany', 1992, 'UEFA', 'Semi-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Germany', 1996, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Croatia', 1996, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Germany', 1996, 'UEFA', 'Quarter-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Croatia', 1996, 'UEFA', 'Quarter-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Israel', 1999, 'UEFA', 'Play-off for Final Tournament', '0-5', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1999, 'UEFA', 'Play-off for Final Tournament', '0-5', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1999, 'UEFA', 'Play-off for Final Tournament', '3-0', 'W');
INSERT INTO Competes_In VALUES('Israel', 1999, 'UEFA', 'Play-off for Final Tournament', '3-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1999, 'UEFA', 'Play-off for Final Tournament', '0-2', 'L');
INSERT INTO Competes_In VALUES('England', 1999, 'UEFA', 'Play-off for Final Tournament', '0-2', 'W');
INSERT INTO Competes_In VALUES('England', 1999, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1999, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 2000, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2000, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 2000, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Israel', 1999, 'UEFA', 'Play-off for Final Tournament', '0-5', 'L');
INSERT INTO Competes_In VALUES('Denmark', 1999, 'UEFA', 'Play-off for Final Tournament', '0-5', 'W');
INSERT INTO Competes_In VALUES('Denmark', 1999, 'UEFA', 'Play-off for Final Tournament', '3-0', 'W');
INSERT INTO Competes_In VALUES('Israel', 1999, 'UEFA', 'Play-off for Final Tournament', '3-0', 'L');
INSERT INTO Competes_In VALUES('Italy', 2000, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 2000, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Final', '2-1', 'W');
INSERT INTO Competes_In VALUES('Italy', 2000, 'UEFA', 'Final', '2-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2000, 'UEFA', 'Quarter-finals', '6-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 2000, 'UEFA', 'Quarter-finals', '6-1', 'L');
INSERT INTO Competes_In VALUES('Turkey', 2000, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2000, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2000, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Italy', 2000, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Romania', 2000, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1999, 'UEFA', 'Play-off for Final Tournament', '0-2', 'L');
INSERT INTO Competes_In VALUES('England', 1999, 'UEFA', 'Play-off for Final Tournament', '0-2', 'W');
INSERT INTO Competes_In VALUES('England', 1999, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Scotland', 1999, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('Slovenia', 1999, 'UEFA', 'Play-off for Final Tournament', '2-1', 'W');
INSERT INTO Competes_In VALUES('Ukraine', 1999, 'UEFA', 'Play-off for Final Tournament', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 2000, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('France', 2000, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2000, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2000, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Slovenia', 1999, 'UEFA', 'Play-off for Final Tournament', '2-1', 'W');
INSERT INTO Competes_In VALUES('Ukraine', 1999, 'UEFA', 'Play-off for Final Tournament', '2-1', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2000, 'UEFA', 'Quarter-finals', '6-1', 'W');
INSERT INTO Competes_In VALUES('Yugoslavia', 2000, 'UEFA', 'Quarter-finals', '6-1', 'L');
INSERT INTO Competes_In VALUES('Slovenia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('France', 2004, 'UEFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Greece', 2004, 'UEFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('France', 2004, 'UEFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Greece', 2004, 'UEFA', 'Quarter-finals', '0-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2004, 'UEFA', 'Final', '0-1', 'L');
INSERT INTO Competes_In VALUES('Greece', 2004, 'UEFA', 'Final', '0-1', 'W');
INSERT INTO Competes_In VALUES('Latvia', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'L');
INSERT INTO Competes_In VALUES('Scotland', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2003, 'UEFA', 'Play-off for Final Tournament', '6-0', 'W');
INSERT INTO Competes_In VALUES('Scotland', 2003, 'UEFA', 'Play-off for Final Tournament', '6-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2004, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2004, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 2003, 'UEFA', 'Play-off for Final Tournament', '2-1', 'W');
INSERT INTO Competes_In VALUES('Norway', 2003, 'UEFA', 'Play-off for Final Tournament', '2-1', 'L');
INSERT INTO Competes_In VALUES('Norway', 2003, 'UEFA', 'Play-off for Final Tournament', '0-3', 'L');
INSERT INTO Competes_In VALUES('Spain', 2003, 'UEFA', 'Play-off for Final Tournament', '0-3', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2004, 'UEFA', 'Semi-finals', '2-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2004, 'UEFA', 'Semi-finals', '2-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2004, 'UEFA', 'Final', '0-1', 'L');
INSERT INTO Competes_In VALUES('Greece', 2004, 'UEFA', 'Final', '0-1', 'W');
INSERT INTO Competes_In VALUES('Wales', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Russia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('Scotland', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 2003, 'UEFA', 'Play-off for Final Tournament', '6-0', 'W');
INSERT INTO Competes_In VALUES('Scotland', 2003, 'UEFA', 'Play-off for Final Tournament', '6-0', 'L');
INSERT INTO Competes_In VALUES('Slovenia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('Spain', 2003, 'UEFA', 'Play-off for Final Tournament', '2-1', 'W');
INSERT INTO Competes_In VALUES('Norway', 2003, 'UEFA', 'Play-off for Final Tournament', '2-1', 'L');
INSERT INTO Competes_In VALUES('Norway', 2003, 'UEFA', 'Play-off for Final Tournament', '0-3', 'L');
INSERT INTO Competes_In VALUES('Spain', 2003, 'UEFA', 'Play-off for Final Tournament', '0-3', 'W');
INSERT INTO Competes_In VALUES('Latvia', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2003, 'UEFA', 'Play-off for Final Tournament', '1-0', 'L');
INSERT INTO Competes_In VALUES('Wales', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'L');
INSERT INTO Competes_In VALUES('Russia', 2003, 'UEFA', 'Play-off for Final Tournament', '0-1', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2008, 'UEFA', 'Quarter-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Quarter-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Semi-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2008, 'UEFA', 'Semi-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Final', '0-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 2008, 'UEFA', 'Final', '0-1', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2008, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('Russia', 2008, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('Portugal', 2008, 'UEFA', 'Quarter-finals', '2-3', 'L');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Quarter-finals', '2-3', 'W');
INSERT INTO Competes_In VALUES('Netherlands', 2008, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('Russia', 2008, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('Russia', 2008, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('Spain', 2008, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Russia', 2008, 'UEFA', 'Semi-finals', '0-3', 'L');
INSERT INTO Competes_In VALUES('Spain', 2008, 'UEFA', 'Semi-finals', '0-3', 'W');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Final', '0-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 2008, 'UEFA', 'Final', '0-1', 'W');
INSERT INTO Competes_In VALUES('Germany', 2008, 'UEFA', 'Semi-finals', '3-2', 'W');
INSERT INTO Competes_In VALUES('Turkey', 2008, 'UEFA', 'Semi-finals', '3-2', 'L');
INSERT INTO Competes_In VALUES('Turkey', 2011, 'UEFA', 'Play-off for Final Tournament', '0-3', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2011, 'UEFA', 'Play-off for Final Tournament', '0-3', 'W');
INSERT INTO Competes_In VALUES('Spain', 2012, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('France', 2012, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Germany', 2012, 'UEFA', 'Quarter-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Greece', 2012, 'UEFA', 'Quarter-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 2012, 'UEFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 2012, 'UEFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Germany', 2012, 'UEFA', 'Quarter-finals', '4-2', 'W');
INSERT INTO Competes_In VALUES('Greece', 2012, 'UEFA', 'Quarter-finals', '4-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 2012, 'UEFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Italy', 2012, 'UEFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Spain', 2012, 'UEFA', 'Final', '4-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 2012, 'UEFA', 'Final', '4-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2012, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('France', 2012, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Spain', 2012, 'UEFA', 'Final', '4-0', 'W');
INSERT INTO Competes_In VALUES('Italy', 2012, 'UEFA', 'Final', '4-0', 'L');
INSERT INTO Competes_In VALUES('Turkey', 2011, 'UEFA', 'Play-off for Final Tournament', '0-3', 'L');
INSERT INTO Competes_In VALUES('Croatia', 2011, 'UEFA', 'Play-off for Final Tournament', '0-3', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1959, 'UEFA', 'Preliminary round', '2-0', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Preliminary round', '2-0', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1959, 'UEFA', 'Preliminary round', '4-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Preliminary round', '4-0', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1963, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Austria', 1963, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1962, 'UEFA', 'Preliminary round', '2-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1962, 'UEFA', 'Preliminary round', '2-1', 'L');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1963, 'UEFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1963, 'UEFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1962, 'UEFA', 'Preliminary round', '4-2', 'W');
INSERT INTO Competes_In VALUES('Iceland', 1962, 'UEFA', 'Preliminary round', '4-2', 'L');
INSERT INTO Competes_In VALUES('Poland', 1962, 'UEFA', 'Preliminary round', '0-2', 'L');
INSERT INTO Competes_In VALUES('Northern Ireland', 1962, 'UEFA', 'Preliminary round', '0-2', 'W');
INSERT INTO Competes_In VALUES('Northern Ireland', 1963, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1963, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1963, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1963, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1964, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1972, 'UEFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('England', 1972, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1972, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1959, 'UEFA', 'Preliminary round', '2-0', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Preliminary round', '2-0', 'L');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1959, 'UEFA', 'Preliminary round', '4-0', 'L');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1959, 'UEFA', 'Preliminary round', '4-0', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1959, 'UEFA', 'Round of 16', '0-2', 'L');
INSERT INTO Competes_In VALUES('Portugal', 1959, 'UEFA', 'Round of 16', '0-2', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1963, 'UEFA', 'Round of 16', '3-2', 'W');
INSERT INTO Competes_In VALUES('Austria', 1963, 'UEFA', 'Round of 16', '3-2', 'L');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1962, 'UEFA', 'Preliminary round', '2-1', 'W');
INSERT INTO Competes_In VALUES('Czechoslovakia', 1962, 'UEFA', 'Preliminary round', '2-1', 'L');
INSERT INTO Competes_In VALUES('German Dem. Rep.', 1963, 'UEFA', 'Round of 16', '1-2', 'L');
INSERT INTO Competes_In VALUES('Hungary', 1963, 'UEFA', 'Round of 16', '1-2', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1962, 'UEFA', 'Preliminary round', '4-2', 'W');
INSERT INTO Competes_In VALUES('Iceland', 1962, 'UEFA', 'Preliminary round', '4-2', 'L');
INSERT INTO Competes_In VALUES('Poland', 1962, 'UEFA', 'Preliminary round', '0-2', 'L');
INSERT INTO Competes_In VALUES('Northern Ireland', 1962, 'UEFA', 'Preliminary round', '0-2', 'W');
INSERT INTO Competes_In VALUES('Northern Ireland', 1963, 'UEFA', 'Round of 16', '0-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1963, 'UEFA', 'Round of 16', '0-1', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1963, 'UEFA', 'Quarter-finals', '5-1', 'L');
INSERT INTO Competes_In VALUES('Spain', 1963, 'UEFA', 'Quarter-finals', '5-1', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1964, 'UEFA', 'Quarter-finals', '0-2', 'L');
INSERT INTO Competes_In VALUES('Spain', 1964, 'UEFA', 'Quarter-finals', '0-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1972, 'UEFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1972, 'UEFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('England', 1972, 'UEFA', 'Quarter-finals', '1-3', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1972, 'UEFA', 'Quarter-finals', '1-3', 'W');
INSERT INTO Competes_In VALUES('USSR', 1972, 'UEFA', 'Final', '3-0', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1972, 'UEFA', 'Final', '3-0', 'W');
INSERT INTO Competes_In VALUES('West Germany', 1976, 'UEFA', 'Quarter-finals', '2-0', 'W');
INSERT INTO Competes_In VALUES('Spain', 1976, 'UEFA', 'Quarter-finals', '2-0', 'L');
INSERT INTO Competes_In VALUES('Yugoslavia', 1976, 'UEFA', 'Semi-finals', '2-4', 'L');
INSERT INTO Competes_In VALUES('West Germany', 1976, 'UEFA', 'Semi-finals', '2-4', 'W');
INSERT INTO Competes_In VALUES('West Germany', 1980, 'UEFA', 'Final', '1-2', 'W');
INSERT INTO Competes_In VALUES('Belgium', 1980, 'UEFA', 'Final', '1-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1988, 'UEFA', 'Semi-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('West Germany', 1988, 'UEFA', 'Semi-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 1988, 'UEFA', 'Quarter-finals', '1-2', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1988, 'UEFA', 'Quarter-finals', '1-2', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 1996, 'UEFA', 'Quarter-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Portugal', 1996, 'UEFA', 'Quarter-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 1996, 'UEFA', 'Final', '1-2', 'L');
INSERT INTO Competes_In VALUES('Germany', 1996, 'UEFA', 'Final', '1-2', 'W');
INSERT INTO Competes_In VALUES('Republic of Ireland', 1995, 'UEFA', 'Play-offs', '0-2', 'L');
INSERT INTO Competes_In VALUES('Netherlands', 1995, 'UEFA', 'Play-offs', '0-2', 'W');
INSERT INTO Competes_In VALUES('Czech Republic', 2004, 'UEFA', 'Quarter-finals', '3-0', 'W');
INSERT INTO Competes_In VALUES('Denmark', 2004, 'UEFA', 'Quarter-finals', '3-0', 'L');
INSERT INTO Competes_In VALUES('Greece', 2004, 'UEFA', 'Semi-finals', '1-0', 'W');
INSERT INTO Competes_In VALUES('Czech Republic', 2004, 'UEFA', 'Semi-finals', '1-0', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2011, 'UEFA', 'Play-off for Final Tournament', '6-2', 'W');
INSERT INTO Competes_In VALUES('Bosnia and Herzegovina', 2011, 'UEFA', 'Play-off for Final Tournament', '6-2', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 2011, 'UEFA', 'Play-off for Final Tournament', '2-0', 'W');
INSERT INTO Competes_In VALUES('Montenegro', 2011, 'UEFA', 'Play-off for Final Tournament', '2-0', 'L');
INSERT INTO Competes_In VALUES('Czech Republic', 2012, 'UEFA', 'Quarter-finals', '0-1', 'L');
INSERT INTO Competes_In VALUES('Portugal', 2012, 'UEFA', 'Quarter-finals', '0-1', 'W');